//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPalestras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assento()
        {
            this.TB_ASSENTO_PALESTRA = new HashSet<Reserva>();
        }
    
        public int id_local { get; set; }
        public short numero_assento { get; set; }
        public Nullable<short> fileira { get; set; }
        public string consevacao { get; set; }
        public string tipo { get; set; }
    
        public virtual Local TB_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> TB_ASSENTO_PALESTRA { get; set; }
    }
}
