//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPalestras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palestra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palestra()
        {
            this.TB_ASSENTO_PALESTRA = new HashSet<Reserva>();
            this.TB_PESSOA = new HashSet<Pessoa>();
        }
    
        public int id_palestra { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> dt_inicio { get; set; }
        public Nullable<int> duracao { get; set; }
        public int id_local { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> TB_ASSENTO_PALESTRA { get; set; }
        public virtual Local TB_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> TB_PESSOA { get; set; }
    }
}
