//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPalestras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class palestrasEntities : DbContext
    {
        public palestrasEntities()
            : base("name=palestrasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assento> TB_ASSENTO { get; set; }
        public virtual DbSet<Reserva> TB_ASSENTO_PALESTRA { get; set; }
        public virtual DbSet<Local> TB_LOCAL { get; set; }
        public virtual DbSet<Palestra> TB_PALESTRA { get; set; }
        public virtual DbSet<Pessoa> TB_PESSOA { get; set; }
    }
}
