//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPalestras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_palestra { get; set; }
        public int id_local { get; set; }
        public short numero_assento { get; set; }
        public Nullable<int> id_pessoa_reservou { get; set; }
        public string compareceu { get; set; }
    
        public virtual Assento TB_ASSENTO { get; set; }
        public virtual Palestra TB_PALESTRA { get; set; }
        public virtual Pessoa TB_PESSOA { get; set; }
    }
}
